apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z $DB_HOST 5432; do echo waiting for postgres; sleep 2; done']
        envFrom:
        - configMapRef:
            name: backend-config
      containers:
      - name: backend
        image: seaexx/task-manager-backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000

        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret