apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskmanager-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - prod.157.230.65.42.nip.io
    secretName: taskmanager-tls-prod
  rules:
  - host: prod.157.230.65.42.nip.io
    http:
      paths:
      - pathType: Prefix
        path: /api
        backend:
          service:
            name: backend-prod
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-prod
            port:
              number: 80
