apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use base configuration
resources:
- namespace.yaml
- ../../base

# Deploy to staging namespace
namespace: prod

# Add -staging suffix to all resources
nameSuffix: -prod

# Add common labels to everything
commonLabels:
  environment: prod
  app.kubernetes.io/managed-by: kustomize

# Override ConfigMap for prod
configMapGenerator:
- name: backend-config
  behavior: merge
  literals:
  - DB_NAME=taskdb-prod
  - DB_HOST=postgres-prod 
  - REDIS_HOST=redis-prod
  - LOG_LEVEL=debug   

- name: postgres-config
  behavior: merge
  literals:
  - POSTGRES_DB=taskdb-prod

- name: frontend-config
  behavior: merge
  literals:
  - API_URL=http://backend-prod:3000

# Override Secret for prod
secretGenerator:
- name: backend-secret
  behavior: merge
  literals:
  - DB_PASSWORD=prod_dbpassword123 

- name: postgres-secret
  behavior: merge
  literals:
  - POSTGRES_PASSWORD=prod_dbpassword123


# Set resource limits ( max for prod)
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 50m
  target:
    kind: Deployment
    name: backend

- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 50m
  target:
    kind: Deployment
    name: postgres

# Backend replicas
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: backend

# Frontend replicas  
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: frontend

# Override HPA for prod (lower max)
- patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 1
    - op: replace
      path: /spec/maxReplicas
      value: 10
  target:
    kind: HorizontalPodAutoscaler
    name: backend-hpa

#override storage for prod
- patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: 10Gi
  target:
    kind: PersistentVolumeClaim
    name: progres-storage

patchesStrategicMerge:
  - ingress-patch.yaml

#