apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: seaexx/task-manager-frontend:latest
        envFrom:
        - configMapRef:
            name: frontend-config
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits: 
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80

